name: Advanced Python Workflow
on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Fixed supported versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No dependencies found"

      - name: Access GitHub Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_KEY }}
        run: echo "Secret value exists, but is hidden from logs"

      - name: Run Python Script
        run: python script.py